import type { NextPage } from 'next'
import Head from 'next/head'
import QuickCard from '../components/quickCard'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RICKLY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='title'>Welcome to Rickly Cricket Tournament Management System!</div>
        <div className='card-wrapper'>
          <QuickCard title='Add Player' link='/player/new' imgSrc='/player.jpg' />
          <QuickCard title='Create Team' link='/team/new' imgSrc='/team.jpg' />
          <QuickCard title='Play Tournament' link='/tournament/new' imgSrc='/tournament.jpg' />
        </div>
      </div>
    </div>
  )
}

export default Home
