import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '../components/sidebar'
import Topbar from '../components/topbar'
import { SearchProvider } from '../hooks/useSearchContext'

const Home: NextPage = () => {
  return (
    <SearchProvider>
      <Head>
        <title>RICKLY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='home'>
        <Sidebar />
        <div className='vertical-container'>
          <Topbar />
          <div className='main-area'>
            
          </div>
        </div>
      </div>
    </SearchProvider>
  )
}

export default Home
