# Generated by Django 4.0.3 on 2022-03-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('match_num', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='team.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('handedness', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=20)),
                ('specifics', models.CharField(default='', max_length=40)),
                ('team', models.ForeignKey(default='Uncapped', on_delete=django.db.models.deletion.SET_DEFAULT, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Time of Match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
        ),
    ]
