# Generated by Django 4.0.3 on 2022-03-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_player_team_alter_team_tournament_playing11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='<function uuid1 at 0x7fbba8445bd0>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default='Idle Teams', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='team.tournament', to_field='name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='<function uuid3 at 0x7fbba8445c60>', max_length=100, unique=True),
        ),
    ]
