# Generated by Django 4.0.3 on 2022-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20220326_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='handedness',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ballhandedness',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bathandedness',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='<function uuid1 at 0x7f2d02bc9bd0>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='<function uuid3 at 0x7f2d02bc9c60>', max_length=100, unique=True),
        ),
    ]
