# Generated by Django 4.0.3 on 2022-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_alter_team_name_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='<function uuid1 at 0x7f3712cf9bd0>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='<function uuid3 at 0x7f3712cf9c60>', max_length=100, unique=True),
        ),
    ]
