# Generated by Django 4.0.3 on 2022-03-30 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_alter_match_date_alter_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinline',
            name='role',
            field=models.CharField(default='fielder', max_length=100),
        ),
        migrations.AddField(
            model_name='playing11',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreline',
            name='ln',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='DNR',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='Point',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loss',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 8, 28, 15, 15973)),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(default='wicketkeeper', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='<function uuid1 at 0x7f5f1dac5bd0>', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='<function uuid3 at 0x7f5f1dac5c60>', max_length=100, unique=True),
        ),
    ]
