# Generated by Django 4.0.3 on 2022-03-30 17:23

from django.db import migrations

def initialize(apps, schema_editor):
    Ap = ['A','B','C','D','E','F','G','H','I','J','K']
    Bp = ['L','M','N','O','P','Q','R','S','T','U','V']
    Tournament = apps.get_model('team','Tournament')
    Player = apps.get_model('team','Player')
    Team = apps.get_model('team','Team')
    t = Tournament(name='APL')
    t.save()
    z = Team(name='Team A',tournament=t)
    z.save()
    z_ = Team(name='Team B',tournament=t)
    z_.save()
    for i in Ap:
        t = Player(name = i, team = z, age = 28, role = 'batter')
        t.save()
    for i in Bp:
        t = Player(name = i, team = z_, age = 28, role = 'batter')
        t.save()
class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_alter_match_date_alter_team_name_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize),
    ]
