# Generated by Django 4.0.3 on 2022-03-31 00:07

from django.db import migrations

def initialize(apps, schema_editor):
    Player = apps.get_model('team','Player')

    for i in range(24):
        t = Player(name = str(i), age = 28, role = 'batter')
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('team', '0037_alter_match_date_alter_team_name_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize)
    ]
